### ISSUE TITLE
Add check for time since last update

### ISSUE THREAD

**Issue by GoogleCodeExporter** [calestyo/check_yum#3]
```
I have written a plugin to check when the last yum update was done. I ripped 
quite a bit of code out of your plugin to do this. I could host it myself, but 
I think it would make sense for it to be hosted with this plugin. 

I'm attaching the plugin, and if you like it then please add it to your 
repository under the same licence. If you don't want to put it in the same repo 
then please say so and I'll put it in its own repo. I'm also happy to do some 
rework (or for you to do some rework) if you think it needs it.
```

Original issue reported on code.google.com by `ham...@aptivate.org` on 17 May 2012 at 1:52

Attachments:
* [check_yum_last_update](https://storage.googleapis.com/google-code-attachments/check-yum/issue-3/comment-0/check_yum_last_update)

**Comment by calestyo** [comment]
I'm just cleaning up old issues and considered this one again.

First, I'm already in very-very-low maintenance mode of check_yum, adding another plugin would probably mean more work ;-)

Second, I wondered a bit, what the last update time actually gives? AFAIU this is the date of the last time any single (or more) packages have been upgraded, right?

What does that information really give? It may have been just one out of many packages that was upgraded, and thus that information doesn't really tell anything about how well the system in question is maintained or not.


So for now at least, I think it's better to keep this separated. Most people will be anyway used to your repo as the location for that plugin :)

**Comment by tkoeck** [comment]
"Second, I wondered a bit, what the last update time actually gives? AFAIU this is the date of the last time any single (or more) packages have been upgraded, right?"

In bigger older companies there are fixed update windows for production systems. Say every quarter of a year. That would be a great tool to have.

**Comment by HariSekhon** [comment]
@tkoeck The All Updates mode of the plugin would seem to cover this situation (btw the upstream maintained version is at https://github.com/harisekhon/nagios-plugins).

I don't know if yum actually stores a "last upgraded" timestamp anywhere, maybe in the rpm db or the last timestamp of the yum.log, but that is updated for any package install too. I think in more cases the All Updates mode is what you want.

**Comment by tkoeck** [comment]
In most cases I would like an activated 'auto update' on all servers and don't have to care about manual updates anymore but we all live in an imperfect world. ;)

**Comment by HariSekhon** [comment]
I toyed with that last decade, too risky for prod really.

Containerization rolling updates supercedes this.
