### ISSUE TITLE
Add verbosity to show packages that need updating

### ISSUE THREAD

**Issue by GoogleCodeExporter** [calestyo/check_yum#5]
```
What steps will reproduce the problem?
1. Run check_yum with -v, -vv, or -vvv

What is the expected output? What do you see instead?
Running with -vvv shows debug output, but none of the other verbosity settings 
show any more info.

Running with -v could show the package list from the yum check-update command, 
and with -vv could show the full output of the yum check-update command, 
including yum plugins used and repositories enabled, etc. -vvv should remain 
unchanged, as the debug output follows Nagios specification.

e.g. ($ indicates command, # indicates output, for demonstration purposes only):
$ check_yum -v
#YUM OK: 0 Security Updates Available. 1 Non-Security Update Available |
#Updates:
#binutils.i386 2.17.50.0.6-20.el5_8.3 updates

$ check_yum -vv
#YUM OK: 0 Security Updates Available. 1 Non-Security Update Available |
#yum check-update output:
#Loaded plugins: fastestmirror, security
#Loading mirror speeds from cached hostfile
# * epel: fedora-epel.mirror.lstn.net
#Skipping security plugin, no data
#
#binutils.i386 2.17.50.0.6-20.el5_8.3 updates

What version of the product are you using? On what operating system?
0.7.1 (or 0.7.2 from 
http://opensource.is/trac/browser/nagios-plugins/check_yum/) on CentOS 5

```

Original issue reported on code.google.com by `Stephen....@gmail.com` on 17 May 2012 at 4:19

**Comment by calestyo** [comment]
I gave this another thought…

Apart from the more easier fixable issues in it, the one with the maximum length for a check's output bothers me.
Having check_yum return the list of upgradeable package is only of use for the admins out there, if they really can rely on that information.
Consider e.g. that an admin uses this info to determine whether he needs to look at the machine and actually do upgrades.
E.g. if openssh-server was in the list of packages with upgrades, he may desperately want to. If it was however say "tree", he may defer it until some later time.
Now when our plugin isn't able to guarantee that it "notices" if content would be cut off, then it may be .e.g openssh-server which gets lost and the admin may not notice that he needs to act.

What I think could be done was that:
The list of upgradable packages is only returned when a special option is given (e.g. --print-upgradeable-packages), which also requires another --nagios-max-plugin-output-length respectively --icinga-max-plugin-output-length to be specified **by the user**, where he sets the exact value of his local installation. If not given, the plugin would fail with UNKNOWN.


Until such patch (along with the issues from above) would be ready, I'm closing this issue.
